# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 028e6752b4a5bf112857be174abe9fb4090a027e18c8a7770f2eef8b5e83a85578b89e8498f55bd49790ab57f0b58644cee540c193976b59ebbba7bdf302ec57

test:
  secret_key_base: 7bb6162b0f1ef838fb5b238e355df8f29d5f7d3d06834d5dacdd5ebfd54c91b08ef503bad36393dc7cd4e5d7619ff865fcc0952c6a721d5e90e30fb8a8c9c8e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
